name: DISCOVERY SERVER CI

on:
  push:
    branches:
      - main
    paths:
      - 'DISCOVERY-SERVER/**'
      - 'docker/backend/discovery-service/**'
      - 'docker-compose.yml'
      - '.github/workflows/discovery-server-*.yml'

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Compile project
        run: |
          cd DISCOVERY-SERVER
          ./mvnw clean compile

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Running unit tests
        run: |
          cd DISCOVERY-SERVER
          ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [ compile, unit-tests ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build project
        run: |
          cd DISCOVERY-SERVER
          ./mvnw clean package

  build-image:
    runs-on: ubuntu-latest
    name: Build Docker Image
    needs: [ build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build project
        run: |
          cd DISCOVERY-SERVER
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd DISCOVERY-SERVER
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: DISCOVERY-SERVER
          file: docker/backend/discovery-service/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/discovery-service:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKER_USERNAME }}/discovery-service:${{github.run_id}}
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}