name: CONFIG SERVER CI

on:
  push:
    branches:
      - main
    paths:
      - 'REVIEW-SERVICE/**'
      - 'docker/backend/review-service/**'
      - 'docker-compose.yml'
      - '.github/workflows/review-service-*.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    name: Test and Build
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Run tests and build
        run: |
          cd REVIEW-SERVICE
          ./mvnw clean verify package

      - name: Extract version
        id: get_version  # Add ID to reference this step
        run: |
          cd REVIEW-SERVICE
          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"  # Debug output

  docker-publish:
    needs: test-and-build
    runs-on: ubuntu-latest
    name: Build and Publish Docker Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: REVIEW-SERVICE
          file: docker/backend/review-service/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/review-service:${{ needs.test-and-build.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/review-service:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ needs.test-and-build.outputs.version }}